using System.Text;

namespace griflib;

public partial class Dags
{
    public static Dictionary<string, string> Help()
    {
        var result = new Dictionary<string, string>
        {
            { "@abs(x)", "Returns the absolute value of x." },
            { "@add(x,y)", "Returns the value of x+y." },
            { "@addlist(key,x)", "Adds value x to the end of list named key." },
            { "@addto(key,x)", "Adds the value of x to the value in key and saves back to key." },
            { "@and", "Used in @if and @while to combine conditions. Stops if false." },
            { "@bitwiseand(x,y)", "Returns a bitwise AND of x and y." },
            { "@bitwiseor(x,y)", "Returns a bitwise OR of x and y." },
            { "@bitwisexor(x,y)", "Returns a bitwise XOR of x and y." },
            { "@cleararray(key)", "Clears all values from array named key." },
            { "@clearbit(x,b)", "Sets bit b in x to 0, with b = 0 to 30." },
            { "@clearlist(key)", "Clears all values from list named key." },
            { "@comment(value)", "Used for comments in scripts. Surround value with quotes." },
            { "@concat(x,y,...)", "Concatenates the values supplied into one string." },
            { "@contains(x,y)", "Returns true/false if string x contains string y." },
            { "@containslist(key1,key2)", "Returns true/false if list key1 contains all values in list key2." },
            { "@datetime(format)", "Returns the current local datetime using .NET format pattern. Timezone in ExtraValue." },
            { "@datetime(format,utc)", "Returns the current UTC datetime using .NET format pattern. UTC in ExtraValue." },
            { "@debug(value)", "If system.debug=true, outputs the value plus a newline. Surround value with quotes." },
            { "@div(x,y)", "Returns integer result of x divided by y. Error if y=0." },
            { "@divto(key,x)", "Sets key to integer result of value in key divided by x. Error if x=0." },
            { "@do", "In a @while loop, marks the end of conditions and starts the statement block." },
            { "@elseif", "If all conditions in an @if are false, starts a new set of conditions. Can be multiple @elseif." },
            { "@else", "If all conditions in @if and all @elseif are false, starts the default block." },
            { "@endfor", "End of @for loop." },
            { "@endforeachkey", "End of @foreachkey loop." },
            { "@endforeachlist", "End of @foreachlist loop." },
            { "@endif", "End of @if block." },
            { "@endwhile", "End of @while loop." },
            { "@eq(x,y)", "Returns true/false if x equals y. Compares as numeric if possible, otherwise as strings ignoring case." },
            { "@exec(value)", "Executes the value as a script. Must surround value with quotes." },
            { "@exists(key)", "Returns true/false if key exists and value is not null or an empty string." },
            { "@flipbit(", "" },
            { "@foreachkey(", "" },
            { "@foreachlist(", "" },
            { "@format(", "" },
            { "@for(x,start,end)", "Runs the @for loop, replacing $x inside with values from start to end inclusive." },
            { "@fromhex(", "" },
            { "@getarray(", "" },
            { "@getbit(", "" },
            { "@getchar(", "" },
            { "@getinchannel", "Get the value sent from calling program sent in \"#INCHANNEL;\"." },
            { "@getlist(", "" },
            { "@getvalue(", "" },
            { "@get(key)", "Gets the value for key." },
            { "@ge(", "" },
            { "@golabel(", "" },
            { "@gt(", "" },
            { "@if", "" },
            { "@inlist(", "" },
            { "@insertatlist(", "" },
            { "@isbool(", "" },
            { "@false(x)", "Returns true/false if x is falsey." },
            { "@isfalse(x)", "Returns true/false if x is falsey." },
            { "@null(", "" },
            { "@isnull(", "" },
            { "@isnumber(", "" },
            { "@isscript(", "" },
            { "@true(x)", "Returns true/false if x is truthy." },
            { "@istrue(x)", "Returns true/false if x is truthy." },
            { "@label(", "" },
            { "@len(", "" },
            { "@le(", "" },
            { "@listlength(", "" },
            { "@lower(", "" },
            { "@lt(", "" },
            { "@max(", "" },
            { "@min(", "" },
            { "@modto(", "" },
            { "@mod(", "" },
            { "@msg(", "" },
            { "@multo(", "" },
            { "@mul(", "" },
            { "@negto(", "" },
            { "@neg(", "" },
            { "@ne(", "" },
            { "@nl", "Add a newline character to the result." },
            { "@not", "" },
            { "@or", "" },
            { "@rand(", "" },
            { "@removeatlist(", "" },
            { "@replace(", "" },
            { "@return", "Exit the current script immediately, returning any results." },
            { "@rnd(", "" },
            { "@script(", "" },
            { "@setarray(", "" },
            { "@setbit(", "" },
            { "@setchar(", "" },
            { "@setextra(", "" },
            { "@setlist(", "" },
            { "@setoutchannel(", "" },
            { "@set(", "" },
            { "@substring(", "" },
            { "@subto(", "" },
            { "@sub(", "" },
            { "@swap(", "" },
            { "@then", "" },
            { "@tobinary(", "" },
            { "@tohex(", "" },
            { "@tointeger(", "" },
            { "@trim(", "" },
            { "@upper(", "" },
            { "@while", "" },
            { "@writeline(", "" },
            { "@write(", "" }
        };
        return result;
    }
}
